### ISSUE TITLE
Put ">" on newline when wrapping multiple attributes

### ISSUE THREAD

**Issue by StarpTech** [StarpTech/prettyhtml#19]
For multiple attributes that extend beyond the printWidth, I would prefer this:

```html
<div
  attr="foo"
  attr="foo"
  attr="foo"
  attr="foo"
>bar</div>
```
over
```html
<div
  attr="foo"
  attr="foo"
  attr="foo"
  attr="foo">bar</div>
```

**Comment by StarpTech** [comment]
Fixed with https://github.com/StarpTech/prettyhtml/pull/20

**Comment by nivv** [comment]
@StarpTech can we have an option to enable/disable this?

**Comment by StarpTech** [comment]
Hi @nivv could you eloborate why? I don't add an option so easily the formatter follows the same philosophy about options as prettier 

https://prettier.io/docs/en/option-philosophy.html

**Comment by nivv** [comment]
@StarpTech I see, I wasn't aware. Languages differ in their style guides. This is awesome for Vue, but if I want to use this for another language the format is "wrong". No worries though!

**Comment by StarpTech** [comment]
@nivv yes, the experiment of this project is to align them all together. There aren't "wrong" formatting here. There are styles and a lot of opinions 😄 I'm trying to be productive and prettyhtml helps a lot to be in teams.
